### ISSUE TITLE
Implement a dedicated page that shows featured design

### ISSUE THREAD

**Issue by akmalroslan** [OrionTopClothing/master#8]

**Comment by skndrmszm** [comment]
![scm-on-going-sale](https://user-images.githubusercontent.com/54976373/84437924-620fcb80-ac68-11ea-844a-0c00f8c3584b.PNG)

A dedicated page that shows on-going sale and featured item for the season! Progress completed

**Comment by skndrmszm** [comment]
![scm-on-going-sale](https://user-images.githubusercontent.com/54976373/84473761-33234500-acbc-11ea-9182-60c3b1744727.PNG)

A dedicated page that shows on-going sale and featured item for the season! Progress completed
